a=int(input("a:"))
b=int(input("b:"))
operation=input("add,sub,multi,div:")
if(operation=="add"):
    print(a+b)
if(operation=="sub"):
    print(a-b)
if(operation=="multi"):
    print(a*b)
if(operation=="div"):
    print(a/b)
